name: Open an Issue
description: This action will open an issue on the repository that triggered the workflow.
author: Matt Compton
branding:
  icon: alert-circle
  color: orange
inputs:
  title:
    description: Issue title
    required: true
    default: "Something's borked"
  body:
    description: Issue body
    required: true
    default: "Something's borked"
  labels:
    description: Issue labels
    required: false
    default: "bug"
  pat:
    description: GitHub Personal Access Token
    required: true
    default: "empty"
  repository:
    description: Repository name
    required: true
    default: "empty"
  owner:
    description: Repository owner
    required: true
    default: "empty"
outputs:
  result:
    description: "Did it work?"
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.owner }}
    - ${{ inputs.repository }}
    - ${{ inputs.pat }}
    - ${{ inputs.title }}
    - ${{ inputs.body }}
    - ${{ inputs.labels }}